default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    :username: <%= ENV["DB_USER"] %>
    :password: <%= ENV["DB_PASS"] %>
  firebase:
    :api_key: <%= ENV["FIRE_BASE_API"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
